server:
  port: 8081

spring:
  application:
    name: spring-ai-bailian
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      agent:
        app-id: ${BAILIAN_SCHOOL_APP_ID}

#    chat:
#      options:
#          model: deepseek-r1





